name: correlate
favicon: null
layout_spectrum: 0.5066445735283196
typography_spectrum: 0.32659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.850212418474257
  lightness: 0.04353937110863626
  saturation: 0.7215169533155859
  rhythmicContrast: 0.1980099338106811
purpose: []
