name: correlate
favicon: null
layout_spectrum: 0.68355
typography_spectrum: 0.54183
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Correlation Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#113035'
    - '#4578bf'
    - '#285872'
    - '#92cff5'
    - '#fefffd'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
