title: correlate
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.375
  brandStrength: 0.8897243
  lightness: 0.5625
  brandColors:
    - '#f1f1f1'
    - '#a0a0a0'
    - '#1b1922'
    - '#ff2f59'
    - '#a03856'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: correlate
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.59982
layout_spectrum: 0.1817043
