name: correlate
favicon: null
layout_spectrum: 0.73321
typography_spectrum: 0.62317
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: correlate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#534733'
    - '#8fa9c0'
    - '#ff7732'
    - '#84756f'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
