name: correlate
favicon: null
layout_spectrum: 0.5183
typography_spectrum: 0.32659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed433d'
    - '#d7de3c'
    - '#ffffff'
    - '#19a79d'
    - '#f3827d'
  brandStrength: 0.5
  lightness: 0.04353937110863626
  saturation: 0.7215169533155859
  rhythmicContrast: 0.1980099338106811
purpose: []
