typography_spectrum: 0.59982
color:
  saturation: 0.375
  brandStrength: 0.8897243
  lightness: 0.5625
  brandColors:
    - '#f1f1f1'
    - '#a0a0a0'
    - '#1b1922'
    - '#ff2f59'
    - '#a03856'
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1817043
analytics:
  twitter: null
  google: null
  facebook: null
name: correlate
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Services
    id: cdd8ba32-3b77-4b39-960b-6d45c45e7eb6
    type: content
  - name: Blog
    id: 873ae52e-12e7-4ac0-92f2-80afcb1669ac
    type: content
  - name: About
    id: 06c2af7b-54e3-486b-980b-3629c8369dd6
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: correlate
purpose: []
