analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.24084
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.75
  brandStrength: 0.5
  rhythmicContrast: 0.75
  brandColors:
    - '#474248'
    - '#a9a19f'
    - '#12090e'
    - '#ac1d30'
    - '#fcd0d3'
  lightness: 0.625
purpose: []
favicon: null
name: correlate
typography_spectrum: 0.32659
